### ISSUE TITLE
Feature request: option to make the build fail when unused files are found

### ISSUE THREAD

**Issue by jasonkarns** [MatthieuLemoine/unused-webpack-plugin#1]
Similar to the [circular-dependency-plugin](https://www.npmjs.com/package/circular-dependency-plugin) where it depends on use case whether finding unused modules should be a hard fail of the build, vs just a warning/print.

I think it makes sense to continue defaulting to warning, but would be nice to have the option to fail the build.

**Comment by MatthieuLemoine** [comment]
@jasonkarns Sure could be nice ! 👍  Feel free to make a PR!

**Comment by jasonkarns** [comment]
sweet, thanks! 🎉
