### ISSUE TITLE
compilation.fileDependencies.filter is not a function

### ISSUE THREAD

**Issue by jovinbm** [MatthieuLemoine/unused-webpack-plugin#3]
My build is currently failing with the error: `TypeError: compilation.fileDependencies.filter is not a function`. Any help will be much appreciated.

Webpack version: 4
unused-webpack-plugin: 1.1.0
config
```
new UnusedWebpackPlugin({
   directories: [path.join(__dirname, 'app/frontend/main')],
   exclude    : ['**/node_modules/**/*', '*.test.js'],
   root       : __dirname
})
```

**Comment by MatthieuLemoine** [comment]
I didn't try the plugin with webpack 4 yet. The API may has changed.

**Comment by jovinbm** [comment]
Thank you.
