### ISSUE TITLE
Disable check for some file

### ISSUE THREAD

**Issue by gaillota** [MatthieuLemoine/unused-webpack-plugin#33]
Hello,

Is it possible to disable this plugin for certain files ? eg. adding a banner `/* unused-webpack-plugin-disable */` on top, eslint-style

Maybe it is a webpack feature that I'm not aware of ?

Thank you and have a good day !

**Comment by MatthieuLemoine** [comment]
You can use the `exclude` [option](https://github.com/MatthieuLemoine/unused-webpack-plugin#options) for this.

**Comment by gaillota** [comment]
Yes, but I was looking for a more friendly way of doing it.

Thank you anyway !
